### ISSUE TITLE
needs to implement value-class-pattern value-title support in dt-* parsing step 1

### ISSUE THREAD

**Issue by tantek** [microformats/php-mf2#60] opened 2014-12-11 20:26 UTC
Per http://microformats.org/wiki/microformats2-parsing#parsing_a_dt-_property the first step is:
-  parse the element for the value-class-pattern including the date and time parsing rules, if a value is found then return it. 

Value-class-pattern support specifically support for value-title:
- http://microformats.org/wiki/value-class-pattern#Parsing_value_from_a_title_attribute

appears to be missing per:
- http://pin13.net/mf2/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Furl%2Fmaster%2Furl.html 

which returns an "updated" property of:
- "updated": ["T"]

whereas it should be:
- "updated": ["20141211"]

(or possibly a newer date)
from the title attribute `title=20141211` in this markup in the source:
- `<span class=dt-updated><span class=value-title title=20141211>11 December 2014</span></span>`

**Comment by gRegorLove** [comment] 2016-06-26 05:38
Reviewing the spec while working on this, I saw:
>Parsing rules for value-title are the same as for value above, with the following change:
* Where a microformats property has a child element with class name of value-title, the content of the title attribute of that element must be parsed, rather than the portion of the element that would be parsed for a class name of value.

When I read [further up on the page](http://microformats.org/wiki/value-class-pattern##if+the+value+has+*only*+a+specific+date), YYYYMMDD does not appear to be a valid format for the parser (emphasis mine):

> * YYYY-MM-DD
* YYYY-DDD
* then use that as the date value. For the purposes of the value class pattern, the **hyphens "-" separating the year, month, day and/or ordinal day are required.**
* ignore any further "value" elements that specify the date.

php-mf2 is finding the YYYYMMDD value correctly, but then it doesn't match those formats. I realize "T" isn't the correct, but I'm not sure what it should be. Blank? No 'updated' property? Or should the spec be udpated to allow YYYYMMDD?

**Comment by tantek** [comment] 2016-06-26 07:07
Note that the master (latest) copy of url.html is using YYYY-MM-DD so this has been fixed in the source document: https://github.com/whatwg/url/blob/master/url.html so we can ignore YYYYMMDD for now.

**Comment by gRegorLove** [comment] 2017-05-28 05:15
Confirmed this is working properly when the date is in a correct format: http://pin13.net/mf2/?id=20170528051422204

**Comment by aaronpk** [comment] 2018-01-12 17:55
I believe this was fixed in #131, but the original HTML in the issue is gone so I don't know the exact input it was failing on.

**Comment by gRegorLove** [comment] 2018-01-13 01:49
@aaronpk Let's leave this open for now. 

I read https://github.com/indieweb/php-mf2/issues/60#issuecomment-228587873 as "authoring issue, ignore." However, I just tested the original HTML with #131 and it parses a space character for `updated`. I'm not sure if it should be an empty string or if `updated` property shouldn't appear at all.

Original HTML:
`<div class="h-entry"><span class=dt-updated><span class=value-title title=20141204>4 December 2014</span></div>`

Parsed using #131:
```

{
    "items": [
        {
            "type": [
                "h-entry"
            ],
            "properties": {
                "updated": [
                    " "
                ],
                "name": [
                    "4 December 2014"
                ]
            }
        }
    ],
    "rels": [],
    "rel-urls": []
}
```

Parsed with latest php-mf2 release:
```
{
    "items": [
        {
            "type": [
                "h-entry"
            ],
            "properties": {
                "updated": [
                    "T"
                ],
                "name": [
                    "4 December 2014"
                ]
            }
        }
    ],
    "rels": {},
    "debug": {
        "package": "https://packagist.org/packages/mf2/mf2",
        "version": "v0.3.2",
        "note": [
            "This output was generated from the php-mf2 library available at https://github.com/indieweb/php-mf2",
            "Please file any issues with the parser at https://github.com/indieweb/php-mf2/issues"
        ]
    }
}
```

**Comment by gRegorLove** [comment] 2018-01-13 02:53
I did some comparisons with other parsers. For YYYYMMDD,

* Node parses it (beyond spec; doesn't seem to cause problems)
* Python returns an empty array for the property
* Ruby parses it (beyond spec, but also adds time precision: "2014-12-04 00:00:00")
* Go parses the node's textContent: "4 December 2014"

When the VCP spec [says](http://microformats.org/wiki/value-class-pattern##If+by+parsing+the+%22value%22+element(s)):
> If by parsing the "value" element(s), at least a specific date has been found, then the "value" is overall valid...

What do we do when the "value" is not overall valid? Should a blank value be returned, or should the property not appear at all?

**Comment by gRegorLove** [comment] 2022-07-05 19:59
Checking with current php-mf2 and I think this is resolved.

With invalid YYYYMMDD format:
```html
<div class="h-entry"><span class=dt-updated><span class=value-title title=20141204>4 December 2014</span></div>
```

Parser no longer returns `updated` as a space or empty string (correct behavior, IMO):
```json
{
    "items": [
        {
            "type": [
                "h-entry"
            ],
            "properties": {
                "name": [
                    "4 December 2014"
                ]
            }
        }
    ]
}
```

With correct YYYY-MM-DD:
```html
<div class="h-entry"><span class=dt-updated><span class=value-title title=2014-12-04>4 December 2014</span></div>
```

Parser returns `updated`:
```json
{
    "items": [
        {
            "type": [
                "h-entry"
            ],
            "properties": {
                "updated": [
                    "2014-12-04"
                ],
                "name": [
                    "4 December 2014"
                ]
            }
        }
    ]
}
```

**Closed by gRegorLove** 2022-07-05 19:59 UTC
Labels: question
