### ISSUE TITLE
Parser returns empty string/unicode entity

### ISSUE THREAD

**Issue by chrisfinazzo** [microformats/php-mf2#223] opened 2021-05-11 15:09 UTC
I have the following HTML which is valid and renders correctly in the preview. Is this a parsing bug or am I doing something else wrong?

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8" />
      <title>Cacio e Pepe</title>
    </head>
    <body>
    <article class="h-entry">
    <h1 class="p-name"><a class="u-url" href="https://www.youtube.com/watch?v=RDNtmeRJCLg">How to Make Instant Ramen Cacio e Pepe with David Chang</a></h1>
    <p class="meta">March 7, 2019</p>
    <p class="e-content">
    <p>Is it the healthiest thing in the world? No. But, damn if it doesn’t look good. One of these days, I’m going to try it - just to see if it lives up to the hype.</p>
    <a href="https://brid.gy/publish/twitter?bridgy_omit_link=true"></a>
    </article>
    </body>
    </html>

_This has been a recurring problem in my "post" template so I tested with just a snippet in a blank document to confirm. Other templates are essentially the same with a few small modifications._

**Comment by barnabywalters** [comment] 2021-05-11 15:16
The problem is with this line:

    <p class="e-content">

The `<p>` element can only contain [phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2), but is itself a flow content element, i.e. `<p>` cannot contain `<p>`. Your HTML is technically valid, but logically false, as browsers/parsers effectively insert a closing `</p>` tag after `<p class="e-content">`, resulting in an empty content string.

You’ll need to wrap all of your e-content in an element which can contain flow content (such as `<div>`) in order for it to be parsed correctly.

**Comment by barnabywalters** [comment] 2021-05-11 15:22
Oh and while we’re discussing markup, you probably want to put the publishing date in a  [`<time class="dt-published">` element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-time-element) inside `p.meta`

**Comment by chrisfinazzo** [comment] 2021-05-11 16:14
Oy.

I originally started with @aaronpk's example, line for line, but somehow didn't pick up where they diverged. Still need to modify the rest of my layouts to mirror this, but this should work now.

    <article class="h-entry">
    <h1 class="p-name"><a class="u-url" href="https://www.youtube.com/watch?v=RDNtmeRJCLg">How to Make Instant Ramen Cacio e Pepe with David Chang</a></h1>
    <div class="meta"><time datetime="2019-03-07" class="dt-published">March 7, 2019</time></div>
    <div class="e-content">
    <p>Is it the healthiest thing in the world? No. But, damn if it doesn’t look good. One of these days, I’m going to try it - just to see if it lives up to the hype.</p>
    </div>
    <a href="https://brid.gy/publish/twitter?bridgy_omit_link=true"></a>
    </article>

**Closed** 2021-05-11 19:39 UTC
